### ISSUE TITLE
JavaScript的原型与原型链

### ISSUE THREAD

**Issue by GGXXMM** [GGXXMM/FE-Knowledge#1]
# 原型(prototype)
### 概念
每个函数创建的时候，其内部会初始化一个prototype属性，prototype属性指向一个对象，这个对象正是调用其构造函数创建的实例的原型。
```
function Person(){}
console.log(typeof Person.prototype)// object
```
![image](https://user-images.githubusercontent.com/13798469/62419007-77f84b80-b6a9-11e9-9c9c-42ad4d062afb.png)
# 原型链(`__proto__`)
### 概念
当访问一个对象的属性时，如果自己内部没有找到该属性，就会向上访问原型对象，一直检索到Object内置对象，从而形成一条由__proto__连接的原型链。
```
function Person(){}
Person.prototype.name = 'zhangsan';
Person.prototype.age = 22;
Person.prototype.say = function(){
     console.log(this.name+','+this.age);
}
var p1 = new Person();
var p2 = new Person();
p2.name = "lisi";
p2.say();// lisi,22
p1.say();// zhangsan,22
```
![image](https://user-images.githubusercontent.com/13798469/62418975-d3760980-b6a8-11e9-8664-143ecc719fa1.png)

**Comment by Guanrui1** [comment]
可以留个联系方式吗？
